// Re-run after adding skills to ~/.hermes/profiles/admin/skills/.
// Usage:  npx tsx scripts/regenerate-skills.ts
//
// This script reads every SKILL.md under ~/.hermes/profiles/admin/skills/
// and rewrites src/data/skills.ts. Pricing logic is the per-category
// fallback table; replace before launch with real numbers.

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { homedir } from "node:os";

const SKILLS_ROOT = `${homedir()}/.hermes/profiles/admin/skills`;
const OUT = `${process.cwd()}/src/data/skills.ts`;

type Skill = {
  name: string;
  category: string;
  path: string;
  description: string;
};

function* walk(dir: string): Generator<string> {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    const s = statSync(p);
    if (s.isDirectory()) yield* walk(p);
    else if (entry === "SKILL.md") yield p;
  }
}

function parse(text: string): { name?: string; description?: string } {
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return {};
  const fm = m[1];
  const desc = fm.match(/^description:\s*(.+)$/m);
  const name = fm.match(/^name:\s*(\S+)/m);
  return {
    name: name?.[1],
    description: desc?.[1].trim().replace(/^['"]|['"]$/g, ""),
  };
}

const skills: Skill[] = [];
for (const path of walk(SKILLS_ROOT)) {
  const text = readFileSync(path, "utf-8");
  const meta = parse(text);
  const rel = relative(SKILLS_ROOT, path).replace(/\/SKILL\.md$/, "");
  const parts = rel.split("/");
  skills.push({
    name: meta.name ?? parts[parts.length - 1],
    category: parts.length > 1 ? parts[0] : "root",
    path: rel,
    description: meta.description ?? "",
  });
}

skills.sort((a, b) => a.name.localeCompare(b.name));

const CAT_UNIT: Record<string, [string, number]> = {
  "creative":             ["per generated asset",     49],
  "github":               ["per repo integration",   149],
  "productivity":         ["per workspace seat",      29],
  "media":                ["per generated minute",    79],
  "research":             ["per query",               19],
  "devops":               ["per deployed service",   199],
  "apple":                ["per device managed",       9],
  "autonomous-ai-agents": ["per agent hour",          12],
  "social-media":         ["per post",                19],
  "email":                ["per inbox connected",     25],
  "smart-home":           ["per room",                 5],
  "gaming":               ["per server hour",          0],
  "data-science":         ["per notebook run",        39],
  "mlops":                ["per model deploy",       199],
  "mcp":                  ["per server connection",   49],
  "note-taking":          ["per vault",                5],
  "red-teaming":          ["per engagement",           0],
  "software-development": ["per PR reviewed",         89],
  "dogfood":              ["per app audited",        299],
};

function offerFor(cat: string): { sku: string; priceUsd: number | null; unit: string; tier: "standard" | "priority" | "enterprise" } {
  const [unit, fallback] = CAT_UNIT[cat] ?? ["per request", 19];
  return {
    sku: `luminara-${cat}-${(skills.find(s => s.category === cat)?.name ?? "x").slice(0, 8)}`,
    priceUsd: fallback,
    unit,
    tier: "standard",
  };
}

const cats = Array.from(new Set(skills.map(s => s.category))).sort();

let body = `// Auto-generated by scripts/regenerate-skills.ts.
// Re-run after adding skills to ~/.hermes/profiles/admin/skills/.

export type SkillCategory =\n`;
body += cats.map(c => `  | "${c}"`).join("\n") + ";\n\n";
body += `export type SkillOffer = {
  sku: string;
  priceUsd: number | null;
  unit: string;
  tier?: "standard" | "priority" | "enterprise";
};

export type Skill = {
  name: string;
  category: SkillCategory;
  path: string;
  description: string;
  offer: SkillOffer;
};

export const SKILLS: Skill[] = [\n`;
for (const s of skills) {
  const o = offerFor(s.category);
  const desc = s.description.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
  body += `  { name: \`${s.name}\`, category: \`${s.category}\`, path: \`${s.path}\`, description: \`${desc}\`, offer: { sku: \`${o.sku}\`, priceUsd: ${o.priceUsd === null ? "null" : o.priceUsd}, unit: \`${o.unit}\`, tier: "${o.tier}" } },\n`;
}
body += `];

export function categories(): SkillCategory[] {
  return Array.from(new Set(SKILLS.map(s => s.category))).sort() as SkillCategory[];
}

export function countByCategory(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const s of SKILLS) out[s.category] = (out[s.category] || 0) + 1;
  return out;
}
`;

writeFileSync(OUT, body, "utf-8");
console.log(`wrote ${OUT} (${skills.length} skills across ${cats.length} categories)`);
